name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1
      - run: rustup update --no-self-update stable
      - run: opam install ocamlbuild
      - run: opam exec -- make -Cinterpreter wasm
      - run: cargo test --all-features
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - run: rustup update --no-self-update stable
      - run: cargo install cargo-deny
      - run: cargo deny check
